// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: boxfox_grpc_client.proto

package demo

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on MonitorReqNew with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MonitorReqNew) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// MonitorReqNewValidationError is the validation error returned by
// MonitorReqNew.Validate if the designated constraints aren't met.
type MonitorReqNewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitorReqNewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitorReqNewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitorReqNewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitorReqNewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitorReqNewValidationError) ErrorName() string { return "MonitorReqNewValidationError" }

// Error satisfies the builtin error interface
func (e MonitorReqNewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitorReqNew.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitorReqNewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitorReqNewValidationError{}

// Validate checks the field values on MonitorRespNew with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *MonitorRespNew) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Errno

	// no validation rules for Errmsg

	return nil
}

// MonitorRespNewValidationError is the validation error returned by
// MonitorRespNew.Validate if the designated constraints aren't met.
type MonitorRespNewValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MonitorRespNewValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MonitorRespNewValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MonitorRespNewValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MonitorRespNewValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MonitorRespNewValidationError) ErrorName() string { return "MonitorRespNewValidationError" }

// Error satisfies the builtin error interface
func (e MonitorRespNewValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMonitorRespNew.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MonitorRespNewValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MonitorRespNewValidationError{}
